spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  batch:
    job:
      enabled: false
      chunk-size: 500
    jdbc:
      initialize-schema: never

logging:
  level:
    com.auction: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"