spring:
  datasource:
    url: jdbc:mysql://auction-rds-db.cnya6424giqr.ap-northeast-2.rds.amazonaws.com:3306/auction
    username: admin
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

logging:
  level:
    org:
      springframework:
        batch: debug