spring:
  profiles:
    active: prod
  config:
    import: optional:file:.env[.properties]

  batch:
    job:
      enabled: false
      chunk-size: 1000
      pool-size: 5
    jdbc:
      initialize-schema: never

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE