spring:
  h2:
    console:
      enabled: true
  datasource:
    master:
      jdbc-url: jdbc:h2:mem:master
      username: sa
      password:
      driver-class-name: org.h2.Driver

    slave:
      jdbc-url: jdbc:h2:mem:master
      username: sa
      password:
      driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core: DEBUG