spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  batch:
    job:
      enabled: false
      chunk-size: 1000
      pool-size: 5
    jdbc:
      initialize-schema: always